### PR TITLE
Finnish translations

### PR DESCRIPTION
**Pull request by retki**
Hi,
Here would be the Finnish translations of the compass.

### CODE REVIEW

**Comment by Kr0oked** [comment]
Thanks a lot!

**Comment by retki** [comment]
You're welcome.😄 When will you release an update that includes these translations?

**Comment by Kr0oked** [comment]
Most likely I will release the next verison on Sunday.
But unfortunately F-Droid needs around a week until it picks my release up and makes it available in the store.

**Comment by retki** [comment]
Great

**Pull request merged**
